apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  namespace: movietrack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      serviceAccountName: catalog-sa
      initContainers:
        - name: wait-for-mysql
          image: mysql:8.0
          command: ['sh', '-c', 'until mysqladmin ping -h mysql-catalog -u root -p$MYSQL_ROOT_PASSWORD --silent; do echo waiting for mysql-catalog; sleep 2; done']
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-catalog-secret
                  key: MYSQL_ROOT_PASSWORD
      containers:
        - name: catalog
          image: 1yacine/movietrack-catalog:latest
          imagePullPolicy: Never
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-catalog-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-catalog-secret
                  key: MYSQL_PASSWORD
          ports:
            - containerPort: 8080
            - containerPort: 9090
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 15
            failureThreshold: 5
